### PR TITLE
Update for 1.9.3 r5

### PR DESCRIPTION
**Pull request by Jyru-Ken**

### CODE REVIEW

**Comment by Buttys** [comment]
Was included in 1.9.5 :D

**Comment by pavelkouril** [comment]
Protip: do the changes in branches and keep Jyru-Ken:master up to date and the diff will be much smaller. :)

**Comment by Jyru-Ken** [comment]
Good tip, but how i can do this ? I'm not a pro :P

**Comment by pavelkouril** [comment]
Write me after this will be merged and I'll tell you how (there's a _slight_ risk this PR could be lost when pushing to the master, since the PR is based on the master and not a branch), it's really easy. :)

**Comment by Jyru-Ken** [comment]
Ready to go :)

**Comment by Buttys** [comment]
Ok, new translations are now available will be included in the next update :D 

check out the new english.xml here https://github.com/Buttys/DevProLauncher/blob/master/Language/English/English.xml (click history to see the exact changes)

**Comment by Buttys** [comment]
Thanks

**Pull request closed without merging**
