### PR TITLE
Checkbox is now checked by default when password is being saved

### PR DESCRIPTION
**Pull request by pavelkouril**
Now when password is being saved, checkbox is not being checked by default and so you lose your lost password easily.

This pull request fixes that. :)

### CODE REVIEW

**Comment by Buttys** [comment]
hmm, i don't want it to save the config on every login because it's not required. it should only have to save it once then once again after the value changes. You only needed that one line of code at the start that i missed.

**Comment by pavelkouril** [comment]
Well, I did it for security purposes; when user doesn't want to save password anymore, we shouldn't keep it in the config file.

**Comment by Buttys** [comment]
simply removing it once save password is unchecked would be enough then. then again you could always encode the password like how it's sent to the server.

**Comment by Buttys** [comment]
Thanks anyways, created an encoded version here https://github.com/Buttys/DevProLauncher/commit/534cfadac21638630ea6a01cbf71d57143e38252

**Pull request closed without merging**
